import { ChakraProvider, Stack } from "@chakra-ui/react";
import { CacheProvider } from "@chakra-ui/next-js";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Style App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        {/* <CacheProvider> */}
        <Stack maxWidth={'1460px'} mx={'auto'}>
          <ChakraProvider>
            <Navbar />
            {children}
            <Footer />
          </ChakraProvider>
        </Stack>

        {/* </CacheProvider> */}
      </body>
    </html>
  );
}
